[project]
name = "expense-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dj-database-url>=3.0.1",
    "django>=5.2.7",
    "gunicorn>=23.0.0",
    "psycopg>=3.2.10",
    "psycopg2-binary>=2.9.11",
    "uvicorn>=0.38.0",
    "whitenoise[brotli]>=6.11.0",
]
