databases:
  - name: budgetdb
    plan: free
    databaseName: budget
    user: samuelchang

services:
  - type: web
    plan: free
    name: budget
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python3 -m gunicorn budget.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4